version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Docker/Dockerfile
        image: namikaze
        volumes:
            - .:/var/www/html
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - laravel
        depends_on:
            - mariadb
            - redis

    mariadb:
        image: mariadb:latest
        ports:
            - '${DB_PORT:-3306}:3306'
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - laravel
        volumes:
            - 'main-mysql:/var/lib/mysql'
            - './storage/app/public/data:/docker-entrypoint-initdb.d:ro'

    redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'main-redis:/data'
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge

volumes:
    main-mysql:
        driver: local
    main-redis:
        driver: local
